steps:
  # Install dependencies for the entire workspace
  - name: "node:20"
    entrypoint: yarn
    args: ["install", "--frozen-lockfile"]
    id: "install-dependencies"

  # Build quin (Cloud Functions)
  - name: "node:20"
    entrypoint: yarn
    args: ["workspace", "quin", "build"]
    id: "build-quin"
    waitFor: ["install-dependencies"]

  # Deploy Cloud Functions (quin)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - "-c"
      - |
        curl -sL https://firebase.tools | bash
        export PATH="$$PATH:/root/.local/bin"
        if [ -z "$$GEMINI_API_KEY" ]; then
          echo "GEMINI_API_KEY secret not available for deployment" >&2
          exit 1
        fi
        export GEMINI_API_KEY="$$GEMINI_API_KEY"
        export GOOGLE_API_KEY="$$GEMINI_API_KEY"
        export FIREBASE_TOKEN=$$(gcloud auth print-access-token)
        firebase deploy --only functions --project lovecentraltexas --non-interactive
    id: "deploy-functions"
    waitFor: ["build-quin"]
    secretEnv: ["GEMINI_API_KEY"]

# Secret configuration for Gemini API key
availableSecrets:
  secretManager:
    - versionName: projects/956360338882/secrets/GEMINI_API_KEY/versions/latest
      env: "GEMINI_API_KEY"

# Build timeout
timeout: "1800s"

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
