steps:
  # Install dependencies for quin
  - name: "node:20"
    entrypoint: "bash"
    id: "Install Dependencies"
    args:
      - "-c"
      - |
        cd packages/quin
        yarn install --frozen-lockfile --network-timeout 300000

  # Build quin (Cloud Functions)
  - name: "node:20"
    entrypoint: "bash"
    id: "Build Quin"
    args:
      - "-c"
      - |
        cd packages/quin
        yarn build

  # Deploy Cloud Functions (quin)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Quin Functions"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        curl -sL https://firebase.tools | bash
        firebase deploy --only functions --project lovecentraltexas --non-interactive --force
    secretEnv: ['GEMINI_API_KEY']

# Secret configuration for Gemini API key
availableSecrets:
  secretManager:
    - versionName: projects/956360338882/secrets/GEMINI_API_KEY/versions/latest
      env: 'GEMINI_API_KEY'

# Build timeout
timeout: '1800s'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY

